- name: Setup the utility location(s)
  hosts: ilo-ironic-nodes
  user: root
  gather_facts: false
  vars:
    utility_address: 172.19.102.222
    ironic_deploy_image_name: ironic-deploy
  tasks:
    - name: create ironic nodes
      shell: |
        . ~/openrc
        if ! ironic node-list | grep "{{ inventory_hostname }}"; then
            ironic node-create \
              -d agent_ipmitool \
              -i ipmi_address="{{ ilo_address }}" \
              -i ipmi_password="{{ ilo_password }}" \
              -i ipmi_username="{{ ilo_user }}" \
              -i deploy_ramdisk="${DEPLOYRAMDISK}" \
              -i deploy_kernel="${DEPLOYKERNEL}" \
              -n {{ inventory_hostname }}
        fi
      delegate_to: "{{ utility_address }}"
      tags:
        - ironic-create
    - name: Create ironic port
      shell: |
        . ~/openrc
        if ! ironic port-list | grep '{{ Port1NIC_MACAddress }}'; then
          ironic port-create \
            -n "$(ironic node-list | awk '/{{ inventory_hostname }}/ {print $2}' )" \
            -a {{ Port1NIC_MACAddress }}
        fi
      delegate_to: "{{ utility_address }}"
      tags:
        - ironic-port
    - name: assosiate image to node
      shell: |
        . ~/openrc
        KERNEL_IMAGE=$(glance image-list | awk '/{{ ironic_deploy_image_name }}.kernel/ {print $2}')
        INITRAMFS_IMAGE=$(glance image-list | awk '/{{ ironic_deploy_image_name }}.initramfs/ {print $2}')
        ironic node-update "$(ironic node-list | awk '/{{ inventory_hostname }}/ {print $2}' )" add \
          driver_info/deploy_kernel=$KERNEL_IMAGE \
          driver_info/deploy_ramdisk=$INITRAMFS_IMAGE \
          instance_info/deploy_kernel=$KERNEL_IMAGE \
          instance_info/deploy_ramdisk=$INITRAMFS_IMAGE \
          instance_info/root_gb=40
      delegate_to: "{{ utility_address }}"
      tags:
        - ironic-image
    - name: add node properties
      shell: |
        . ~/openrc
        ironic node-update "$(ironic node-list | awk '/{{ inventory_hostname }}/ {print $2}' )" add \
          properties/cpus=48 \
          properties/memory_mb=254802 \
          properties/local_gb=80 \
          properties/size=3600 \
          properties/cpu_arch=x86_64 \
          properties/capabilities=memory_mb:254802,local_gb:80,cpu_arch:x86_64,cpus:48,boot_option:local
      delegate_to: "{{ utility_address }}"
      tags:
        - ironic-properties
